name: Mirror main and tags to GitLab
on:
  push:
    branches: [ main ]
    tags: [ '*' ]

jobs:
  mirror:
    if: ${{ github.actor != 'mirror-bot' }}  # avoid loops if you later use this name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure git user
        run: |
          git config user.name  "mirror-bot"
          git config user.email "mirror-bot@noreply.example"
      - name: Add GitLab remote
        env:
          GL_TOKEN: ${{ secrets.GL_TOKEN }}        # GitLab PAT
          GL_URL:   ${{ secrets.GL_URL }}          # e.g. https://git.civicactions.net
          GL_REPO:  ${{ secrets.GL_REPO }}         # mike.gifford/foss4gov
        run: |
          git remote add gitlab "https://oauth2:${GL_TOKEN}@${GL_URL#https://}/${GL_REPO}.git"
          git remote -v
      - name: Push branches and tags
        run: |
          git push --prune --follow-tags gitlab +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*
