# .github/workflows/replicate-to-gitlab.yml
name: Replicate PR branch to GitLab and open MR
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  replicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Push PR branch to GitLab
        env:
          GL_TOKEN: ${{ secrets.GL_TOKEN }}
          GL_URL:   ${{ secrets.GL_URL }}
          GL_REPO:  ${{ secrets.GL_REPO }}
          PR_BRANCH: ${{ github.head_ref }}
        run: |
          git config user.name  "replicate-bot"
          git config user.email "replicate-bot@example.org"
          git remote add gitlab "https://oauth2:${GL_TOKEN}@${GL_URL#https://}/${GL_REPO}.git"
          git push -u gitlab "HEAD:refs/heads/pr/${{ github.event.number }}-${PR_BRANCH}"
      - name: Open or update MR on GitLab
        env:
          GL_TOKEN: ${{ secrets.GL_TOKEN }}
          GL_API:   ${{ secrets.GL_URL }}/api/v4
          GL_PID:   ${{ secrets.GL_PROJECT_ID }}  # numeric project ID
        run: |
          curl -s --header "PRIVATE-TOKEN: ${GL_TOKEN}" \
            -X POST "${GL_API}/projects/${GL_PID}/merge_requests" \
            --data "source_branch=pr/${{ github.event.number }}-${{ github.head_ref }}" \
            --data "target_branch=main" \
            --data-urlencode "title=[GitHub PR #${{ github.event.number }}] ${{ github.event.pull_request.title }}" \
            --data-urlencode "description=${{ github.event.pull_request.html_url }}"
